### ISSUE TITLE
Excerpt processing outputs automatic excerpts even if manual excerpts are defined

### ISSUE THREAD

**Issue by mfessler** [markcheret/footnotes#65] opened 2021-03-31 14:43 UTC
Sometime in the last few releases, Footnotes started ignoring the manual excerpts I have defined for all of my posts, and instead all excerpts that my theme outputs are the automatic ones generated by WordPress. This was true whether I had DIsplay Footnotes in Excerpts turned on or off. 

It's possible to work around this by disabling the the_excerpt hook under Scope and Priority (once you know that Footnotes is the problem.)

Usually, the excerpts were formatted as plain text, which made this harder to debug. Today, formatting was included in the excerpts as well, e.g. an H4 placed at the top of the post as a subhead. (This finally led me to investigate whether Footnotes was the issue, since I had just updated it. After turning the_excerpt off and on, I can't reproduce it, though.)

Proposed fix: if a post has a manual excerpt defined, a) use it and b) pass it through unmodified, since they are plain text without any embedded shortcodes or other markup.

**Comment by markcheret** [comment] 2021-04-04 19:53
Hi @mfessler thank you for opening an issue here in our GitHub.
I assigned @pewgeuges who's capable of assisting you with the bug you're experiencing.
best wishes
Mark

**Comment by pewgeuges** [comment] 2021-04-05 18:39
@mfessler

> Sometime in the last few releases, Footnotes started ignoring the manual excerpts I have defined for all of my posts,

I apologize for ignoring the manual excerpts. Since you have manual excerpts, you need to disable the `the_excerpt` hook filter in Footnotes as you did.

> and instead all excerpts that my theme outputs are the automatic ones generated by WordPress.

These are actually generated by Footnotes. Since v2.6.2 released on March 28, the No option, and since v2.6.3 the Yes option are effective. Previously, Footnotes tried to process footnotes in the finished excerpt if set to Yes. Now I realize that footnotes can be present in manual excerpts to display tooltips. But then, the No option is sort of weird given it would leave those footnotes unprocessed.

> This was true whether I had DIsplay Footnotes in Excerpts turned on or off.

When this setting is set to No, footnotes are removed from the content before generating the excerpt in plain text. If it’s set to Yes, footnotes are removed then readded at the end and processed for tooltips. Consistently then the excerpt keeps other formatting as well except paragraph and line breaks (also between list items).

> It's possible to work around this by disabling the the_excerpt hook under Scope and Priority (once you know that Footnotes is the problem.)

This hook is now default-disabled. Probably we should better document this but basically the bug was about `the_excerpt` doing nearly nothing, nothing at all for footnotes in the post: Idle referrers and full tooltip texts were part of the excerpt! Before the bug was fixed (fully since 2.6.3).

> Usually, the excerpts were formatted as plain text, which made this harder to debug.

The footnotes were processed only to be wrecked by deleting their markup.

> Today, formatting was included in the excerpts as well,

When Display footnotes in excerpts is set to Yes (see above).

> e.g. an H4 placed at the top of the post as a subhead.

Yes I noticed this when debugging the setting. If the heading starts the excerpt as plain text, it should be followed by an em dash. That was too much options. For a more fine-grained tuning like in the Advanced Excerpts plugin there was not enough time.

> (This finally led me to investigate whether Footnotes was the issue, since I had just updated it. After turning the_excerpt off and on, I can't reproduce it, though.)

I don’t understand what is not reproducible when unchecking the_excerpt.

> Proposed fix: if a post has a manual excerpt defined, a) use it

I’m not capable of coding this solution.

@markcheret It is inappropriate to make assumptions about what I’m capable of. I’m a user coming up with a bunch of bugfixes in October, you granted me SVN commit access, I was given to fix bugs and add missing settings and features during five months until I was done and you devised to cancel my commit access, incapacitating me for timely providing fixes as required. I’m unlikely to keep posting here either.

> and b) pass it through unmodified, since they are plain text without any embedded shortcodes or other markup.

That depends on the post author. WordPress specifies that every markup will be kept, and we can actually have hyperlinks in manual excerpts, as well as everything else.

As of shortcodes, since we know about it, we cannot assume that all users don’t have footnotes in manual excerpts. If they do, I’ve inadvertently broken them! I’m sorry about that!

**Comment by markcheret** [comment] 2021-04-15 23:37
I understand this issue has been addressed in our 2.7.0 releases.

**Closed by markcheret** 2021-04-15 23:37 UTC
Labels: bug, documentation
